'use client'

import { useEffect, useMemo, useRef, useState } from 'react'

type Scene = 'intro' | 'message' | 'card' | 'reveal' | 'countdown' | 'finale'
const PHOTO_SRC = '/vetha1.jpeg'
const messageLines = ['Vetha 💜...', 'Direct-ah birthday wish pannalam nu nenachen...', 'Aana, oru normal "Happy Birthday" message anupuradha vida, konjam different-ah wish pannalam nu thonuchu. 🤍', 'So... indha chinna surprise unakkaga.', 'Eppovume happy-ah iru, sirichite iru. 🤍', 'Innaiku un day... so vibe, smile, and enjoy! 😌']

function ParticleField() { const ref = useRef<HTMLCanvasElement>(null); useEffect(() => { const canvas = ref.current, ctx = canvas?.getContext('2d'); if (!canvas || !ctx) return; let frame=0; const particles=Array.from({length:28},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.2+.35,a:Math.random()*.35+.08,s:Math.random()*.0002+.00006})); const resize=()=>{const ratio=Math.min(devicePixelRatio,2); canvas.width=innerWidth*ratio; canvas.height=innerHeight*ratio; canvas.style.width=`${innerWidth}px`; canvas.style.height=`${innerHeight}px`; ctx.setTransform(ratio,0,0,ratio,0,0)}; const draw=()=>{ctx.clearRect(0,0,innerWidth,innerHeight); particles.forEach(p=>{p.y-=p.s;if(p.y<-.02)p.y=1.02;ctx.beginPath();ctx.fillStyle=`rgba(205,190,234,${p.a})`;ctx.arc(p.x*innerWidth,p.y*innerHeight,p.r,0,Math.PI*2);ctx.fill()});frame=requestAnimationFrame(draw)};resize();addEventListener('resize',resize);frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize)}},[]); return <canvas ref={ref} className="particle-field" aria-hidden="true"/> }
function Fireworks({active}:{active:boolean}) { const ref=useRef<HTMLCanvasElement>(null); useEffect(()=>{if(!active)return;const canvas=ref.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;let frame=0,lastBurst=-1000,started=performance.now();const sparks:{x:number;y:number;vx:number;vy:number;life:number;color:string}[]=[];const resize=()=>{const ratio=Math.min(devicePixelRatio,2);canvas.width=innerWidth*ratio;canvas.height=innerHeight*ratio;canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(ratio,0,0,ratio,0,0)};const burst=()=>{const x=innerWidth*(.16+Math.random()*.68),y=innerHeight*(.14+Math.random()*.38),colors=['#ead7a1','#d8c7f2','#fff9e9'];for(let i=0;i<42;i++){const angle=Math.PI*2*i/42,speed=1+Math.random()*2.2;sparks.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:1,color:colors[i%colors.length]})}};const draw=(time:number)=>{ctx.clearRect(0,0,innerWidth,innerHeight);if(time-lastBurst>760&&time-started<6200){burst();lastBurst=time}sparks.forEach(s=>{s.x+=s.vx;s.y+=s.vy;s.vy+=.018;s.life-=.012;ctx.globalAlpha=Math.max(0,s.life);ctx.fillStyle=s.color;ctx.shadowBlur=8;ctx.shadowColor=s.color;ctx.beginPath();ctx.arc(s.x,s.y,1.25,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;ctx.shadowBlur=0;frame=requestAnimationFrame(draw)};resize();addEventListener('resize',resize);frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize)}},[active]); return <canvas ref={ref} className="fireworks" aria-hidden="true"/> }
function Confetti({active}:{active:boolean}) { const pieces=useMemo(()=>Array.from({length:26},(_,i)=>({id:i,left:Math.random()*100,delay:Math.random()*1.4,duration:3.4+Math.random()*2.6,color:i%3===0?'var(--gold)':i%3===1?'var(--lavender)':'#fff2d0',size:5+Math.random()*5})),[]); if(!active)return null; return <div className="confetti-field" aria-hidden="true">{pieces.map(p=><span key={p.id} className="confetti-piece" style={{left:`${p.left}%`,animationDelay:`${p.delay}s`,animationDuration:`${p.duration}s`,background:p.color,width:p.size,height:p.size*1.4}}/>)}</div> }
function BirthdayLetters(){const renderLetters=(text:string,offset:number)=>[...text].map((letter,index)=><span key={`${offset}-${index}`} className="birthday-letter" style={{'--letter-delay':`${offset+index*.075}s`} as React.CSSProperties}>{letter===' '?'\u00a0':letter}</span>);return <h2 className="birthday-letters" aria-label="Happy Birthday Vetha"><span className="birthday-row">{renderLetters('HAPPY BIRTHDAY',.2)}</span><span className="birthday-row">{renderLetters('VETHA 💜',1.25)}</span></h2>}

export default function Page(){
 const [scene,setScene]=useState<Scene>('intro'),[line,setLine]=useState(0),[flipped,setFlipped]=useState(false),[count,setCount]=useState(3),[photoReady,setPhotoReady]=useState(false); const cardRef=useRef<HTMLButtonElement>(null)
 useEffect(()=>{const image=new Image();image.decoding='async';image.src=PHOTO_SRC;image.onload=()=>setPhotoReady(true)},[])
 useEffect(()=>{if(scene!=='message'||line>=messageLines.length)return;const timer=setTimeout(()=>setLine(v=>v+1),line===0?1300:2100);return()=>clearTimeout(timer)},[scene,line])
 useEffect(()=>{if(scene!=='countdown')return;if(count>0){const timer=setTimeout(()=>setCount(v=>v-1),900);return()=>clearTimeout(timer)}const timer=setTimeout(()=>setScene('finale'),700);return()=>clearTimeout(timer)},[scene,count])

 const progress=(['intro','message','card','reveal','countdown','finale'].indexOf(scene)+1)/6*100
 return <main className={`birthday-app scene-${scene}`}><ParticleField/><Fireworks active={scene==='finale'}/><Confetti active={scene==='finale'}/>
 {scene==='intro'&&<section className="scene-content intro-content"><div className="intro-badge">a little surprise for you</div><div className="intro-lines"><p className="intro-hero"><span>Oiii</span> madam</p><p className="intro-teaser">I made something small, soft, and special.</p></div><span className="intro-divider" aria-hidden="true"/><button className="outline-button" onClick={()=>setScene('message')}>Open your surprise <span aria-hidden="true">→</span></button></section>}
 {scene==='message'&&<section className="scene-content message-content"><div className="personal-message" aria-live="polite">{messageLines.map((text,index)=><p key={text} className={index<line?'visible':''}>{text.split('\n').map((part,i)=><span key={part}>{part}{i<text.split('\n').length-1&&<br/>}</span>)}</p>)}</div>{line>=messageLines.length&&<button className="text-button" onClick={()=>setScene('card')}>Keep going <span aria-hidden="true">↓</span></button>}</section>}
 {scene==='card'&&<section className="scene-content card-content"><p className="eyebrow">A small reminder</p><button ref={cardRef} className={`flip-card ${flipped?'is-flipped':''}`} onClick={()=>setFlipped(v=>!v)} aria-label={flipped?'Show front of card':'Flip card to read the message'}><span className="card-face card-front"><span className="card-mark">V</span><span>Whenever you forget how special you are</span><small>tap to open</small></span><span className="card-face card-back"><span>“You make ordinary moments feel worth remembering.”</span></span></button>{flipped&&<button className="text-button" onClick={()=>setScene('reveal')}>One more thing <span aria-hidden="true">→</span></button>}</section>}
 {scene==='reveal'&&<section className="scene-content reveal-content"><div className={`portrait-wrap ${photoReady?'is-ready':''}`}><div className="portrait-glow"/><span className="frame-corner corner-tl"/><span className="frame-corner corner-tr"/><span className="frame-corner corner-bl"/><span className="frame-corner corner-br"/><img src={PHOTO_SRC} alt="A special memory" className="portrait"/></div><p className="tap-hint">a little memory, just for you</p><p className="reveal-message">Some moments just look better without trying.</p><button className="text-button" onClick={()=>setScene('countdown')}>Finish the surprise <span aria-hidden="true">→</span></button></section>}
 {scene==='countdown'&&<section className="scene-content countdown-content" aria-live="assertive"><span className="count-ring" key={count}/><div className="count-number" key={count}>{count}</div></section>}
 {scene==='finale'&&<section className="scene-content finale-content"><BirthdayLetters/><p className="finale-note">Made with <span>🫰</span>, especially for you</p><button className="replay-button" onClick={()=>{setScene('intro');setLine(0);setFlipped(false);setCount(3)}}>Replay ↻</button></section>}
 <div className="progress" aria-hidden="true"><span style={{width:`${progress}%`}}/></div></main>
}
